# Generated by Django 6.1 on 2026-08-15 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0003_service_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_roles', to='catalog.laboratory'),
        ),
    ]
