# Generated by Django 6.1 on 2026-08-11 06:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictServerConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_url', models.URLField(blank=True, help_text='Masalan: https://arnasoy-ses.uz/api')),
                ('stats_path', models.CharField(default='/stats/', help_text="base_url'ga qo'shiladigan statistika endpointi", max_length=200)),
                ('auth_type', models.CharField(choices=[('none', "Yo'q (ochiq)"), ('api_key', 'API kalit (maxsus header)'), ('bearer', 'Bearer token'), ('basic', 'Login/parol (Basic auth)')], default='none', max_length=20)),
                ('api_key_header', models.CharField(blank=True, default='X-API-Key', help_text="'API kalit' rejimida ishlatiladigan header nomi", max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=300)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=300)),
                ('is_enabled', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='server_config', to='catalog.district')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
