# Generated by Django 6.1 on 2026-08-11 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_districtserverconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='district',
            field=models.ForeignKey(blank=True, help_text="Bo'sh = barcha tumanlar uchun umumiy xizmat. To'ldirilsa, faqat shu tuman qabulida tanlash mumkin.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='catalog.district'),
        ),
    ]
