# Generated by Django 6.1 on 2026-08-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='conclusion_template',
            field=models.CharField(blank=True, choices=[('', 'Umumiy (standart) xulosa blankasi'), ('brutselloz_ifa', 'Bruselloz IFA (IgM/IgG)'), ('trichomonas_candida_ifa', 'Trichomonas/Candida IFA (IgM/IgG)'), ('echinokokk_ifa', 'Exinokokk IFA (IgM/IgG)'), ('brutselloz_serological', 'Bruselloz seroligik xulosasi (Heddelson/Rayt)')], default='', help_text="Bo'sh = umumiy xulosa blankasi ishlatiladi.", max_length=50),
        ),
    ]
