# Generated by Django 6.1 on 2026-09-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_service_conclusion_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='conclusion_template',
            field=models.CharField(blank=True, default='', help_text="Xulosa blankasi shabloni. Bo'sh = umumiy xulosa blankasi ishlatiladi.", max_length=60),
        ),
    ]
