# Generated by Django 6.1 on 2026-08-11 04:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('last_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_key', models.CharField(max_length=8, unique=True)),
                ('last_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('operator_id', models.UUIDField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=200, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_method', models.CharField(default='naqd', max_length=30)),
                ('payment_status', models.CharField(default='tolanmagan', max_length=30)),
                ('process_status', models.CharField(default='qabul_qilindi', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='clients.client')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='catalog.district')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=300)),
                ('sample_type', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity', models.IntegerField(default=1)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='admissions.admission')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_items', to='catalog.district')),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_items', to='catalog.laboratory')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_items', to='catalog.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=300)),
                ('sample_type', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='yangi', max_length=30)),
                ('result_text', models.TextField(blank=True, null=True)),
                ('result_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=200, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='admissions.admission')),
                ('admission_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='admissions.admissionitem')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='clients.client')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='catalog.district')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='catalog.laboratory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('method', models.CharField(default='naqd', max_length=30)),
                ('operator_id', models.UUIDField(blank=True, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='admissions.admission')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='catalog.district')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
