# Generated by Django 6.1 on 2026-09-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='conclusion_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='laborder',
            name='conclusion_template',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='laborder',
            name='conclusion_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
