# Generated by Django 6.1 on 2026-08-11 04:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('birth_year', models.CharField(max_length=4)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('pinfl', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10, null=True)),
                ('region', models.CharField(default='Jizzax viloyati', max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('workplace', models.CharField(max_length=300)),
                ('visit_type', models.CharField(blank=True, max_length=200, null=True)),
                ('client_code', models.CharField(blank=True, max_length=50, null=True)),
                ('service_type', models.CharField(default='Laboratoriya tekshiruvi', max_length=300)),
                ('status', models.CharField(default='yangi', max_length=30)),
                ('payment_status', models.CharField(default='kutilmoqda', max_length=30)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='catalog.district')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
