# Generated by Django 6.1 on 2026-08-11 04:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='Epidemiologiya', max_length=100)),
                ('severity', models.CharField(choices=[('new', 'Yangi'), ('urgent', 'Shoshilinch'), ('completed', 'Yakunlangan')], default='new', max_length=20)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'news',
                'ordering': ['-published_at'],
            },
        ),
    ]
